name: solvespace
base: core18
summary: Parametric 2d/3d CAD
icon: icons/solvespace.svg
adopt-info: solvespace
description: |
  SOLVESPACE is a free (GPLv3) parametric 3d CAD tool. 
 
  Applications include
  * modeling 3d parts — draw with extrudes, revolves, and Boolean (union / difference) operations
  * modeling 2d parts — draw the part as a single section, and export DXF, PDF, SVG; use 3d assembly to verify fit
  * 3d-printed parts — export the STL or other triangle mesh expected by most 3d printers
  * preparing CAM data — export 2d vector art for a waterjet machine or laser cutter; or generate STEP or STL, for import into third-party CAM software for machining
  * mechanism design — use the constraint solver to simulate planar or spatial linkages, with pin, ball, or slide joints
  * plane and solid geometry — replace hand-solved trigonometry and spreadsheets with a live dimensioned drawing

grade: stable
confinement: strict

layout:
  /usr/share/solvespace:
    bind: $SNAP/usr/share/solvespace

plugs:
  gnome-3-28-1804: # will be replaced by gnome extension
    interface: content
    target: gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804
  gtk-3-themes: # will be replaced by gnome extension
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes: # will be replaced by gnome extension
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes: # will be replaced by gnome extension
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes

apps:
  solvespace:
    command: desktop-launch solvespace
    plugs: [opengl, x11, unity7, wayland, desktop, home, removable-media, gsettings, network]
    desktop: usr/share/applications/solvespace.desktop
    environment:
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/usr/share/glvnd/egl_vendor.d
  solvespace-cli:
    command: solvespace-cli
parts:
  icon:
    plugin: dump
    source: icons

  solvespace:
    after: [desktop-gtk3]
    plugin: cmake
    source: https://github.com/solvespace/solvespace.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "3.0.0~git$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)"
      git submodule update --init extlib/libdxfrw
    override-stage: |
      snapcraftctl stage
      # patch desktop file with correct icon path
      SED_CMD="sed -i -E s|^Icon=(.*)|Icon=\${SNAP}/solvespace.svg|g"
      $SED_CMD usr/share/applications/solvespace.desktop
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_TESTS=OFF
    build-packages:
      - zlib1g-dev 
      - libpng-dev
      - libcairo2-dev 
      - libfreetype6-dev 
      - libjson-c-dev
      - libfontconfig1-dev 
      - libgtkmm-3.0-dev 
      - libpangomm-1.4-dev 
      - libgl-dev 
      - libglu-dev 
      - libspnav-dev
    stage-packages:
      - libspnav0
      - libatkmm-1.6-1v5
      - libcairomm-1.0-1v5
      - libgtkmm-3.0-1v5
      - libglibmm-2.4-1v5
      - libpangomm-1.4-1v5
      - libsigc++-2.0-0v5
      - libglew2.0
      - libegl-mesa0

  desktop-gtk3: # will be replaced by gnome extension
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3